### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by Moredread** [fizyk20/rust-mpfr#11]
It seems that almost all operations are thread safe, as the state is only changed using mpfr functions. So shouldn't Mpfr be also Sync?

On the other hand the default precision is thread local, so exposing it seems also to mean, that Mpfr is not exactly Send atm. Is it worth to expose it if this mean we lose Sync and/or Send?

**Comment by Moredread** [comment]
Oh, of course that all makes only sense of mpfr is compiled with thread safety enabled. I guess that should be mentioned in the Readme?

**Comment by fizyk20** [comment]
I haven't given it much thought, tbh. I'll have to explore how the mpfr library is interacting with threading ;)

**Comment by Moredread** [comment]
See PR #13

**Comment by fizyk20** [comment]
Hmm, I looked at the problem closer. Is thread-local default precision really non-Send? I mean, an existing Mpfr struct has a defined precision already, so sending it across threads doesn't interact with the default precision at all.

Making Mpfr Sync does seem to make sense, so I'll merge the PR :)

**Comment by Moredread** [comment]
Great :)

Yes, it seems you are right, I have overthought the problem it seems.
